-- 실습 10

-- 거래 테이블에서 계좌별 누적 거래 금액을 계산하시오.
SELECT
    ACCOUNT_ID,
    SUM(AMOUNT) OVER(PARTITION BY ACCOUNT_ID
    ORDER BY ACCOUNT_ID
--    ROWS UNBOUNDED PRECEDING
    ) AS CUM_AMOUNT
FROM TRANSACTIONS;

SELECT
    ACCOUNT_ID,
    MAX(AMOUNT) OVER(PARTITION BY ACCOUNT_ID) AS MAX_AMOUNT
FROM TRANSACTIONS;

SELECT
    BRANCH_ID,
    SUM(AMOUNT) OVER(PARTITION BY BRANCH_ID
    ORDER BY LOAN_ID
    ROWS UNBOUNDED PRECEDING) AS CUM_AMOUNT
FROM LOANS;

SELECT
    CUSTOMER_ID,
    ROUND(AVG(BALANCE) OVER(PARTITION BY CUSTOMER_ID), 2)
    AS AVG_BALANCE
FROM ACCOUNTS;