-- 실습 10

-- 1.거래 테이블에서 계좌별 누적 거래 금액을 계산하시오.
SELECT
    ACCOUNT_ID,AMOUNT,TRANSACTION_DATE,
    SUM(AMOUNT) OVER(PARTITION BY ACCOUNT_ID
    ORDER BY TRANSACTION_DATE
    ROWS UNBOUNDED PRECEDING
--    RANGE UNBOUNDED PRECEDING
    ) AS CUM_AMOUNT
FROM TRANSACTIONS;

-- 2.각 계좌별 거래 금액의 최고 거래 금액 대비 비율을 출력하시오.
SELECT
    ACCOUNT_ID,
    ROUND(AMOUNT/MAX(AMOUNT) OVER(PARTITION BY ACCOUNT_ID),3) AS MAX_AMOUNT_PORTION
FROM TRANSACTIONS;

-- 3.대출 테이블에서 지점별 누적 대출 금액을 계산하시오.
SELECT
    BRANCH_ID,
    SUM(AMOUNT) OVER(PARTITION BY BRANCH_ID
    ORDER BY LOAN_DATE
    ROWS UNBOUNDED PRECEDING) AS CUM_AMOUNT
FROM LOANS
WHERE STATUS = 'APPROVED';

-- 4.계좌 테이블에서 고객별 평균 잔액을 계산하시오.
SELECT
    DISTINCT CUSTOMER_ID,
    ROUND(AVG(BALANCE) OVER(PARTITION BY CUSTOMER_ID), 2)
    AS AVG_BALANCE
FROM ACCOUNTS
ORDER BY CUSTOMER_ID;
