-- 실습8
SELECT C.NAME
FROM CUSTOMERS C,
    (SELECT L.CUSTOMER_ID
    FROM LOANS L, BRANCHES B
    WHERE L.BRANCH_ID = B.BRANCH_ID AND LOCATION = 'Location 1') T
WHERE T.CUSTOMER_ID = C.CUSTOMER_ID
;

SELECT *
FROM TRANSACTIONS
WHERE ACCOUNT_ID IN (
    SELECT ACCOUNT_ID
    FROM ACCOUNTS
    WHERE CUSTOMER_ID = 100);
    
SELECT A1.ACCOUNT_ID, BALANCE
FROM ACCOUNTS A1
WHERE BALANCE = (SELECT MAX(BALANCE)
    FROM ACCOUNTS A2
    WHERE A1.ACCOUNT_ID = A2.ACCOUNT_ID)
;