ALTER SESSION SET STATISTICS_LEVEL=ALL;

-- OR
SELECT * FROM EMPLOYEES
WHERE EMP_NO LIKE '101%'
OR EMP_NO LIKE '103%';

-- UNION ALL
SELECT * FROM EMPLOYEES
WHERE EMP_NO LIKE '101%'
UNION ALL
SELECT * FROM EMPLOYEES
WHERE EMP_NO LIKE '103%';

-- PK DATATYPE에 맞춘 WHERE절
SELECT * FROM EMPLOYEES
WHERE (EMP_NO BETWEEN 10100 AND 10299)
    OR (EMP_NO BETWEEN 10300 AND 10399)
;

-- 기존 함수
SELECT NVL(gender, 'NON') AS gender, COUNT(*)
FROM EMPLOYEES
GROUP BY NVL(gender, 'NON');

-- 개선
SELECT gender, COUNT(*)
FROM EMPLOYEES
GROUP BY gender
;

-- 기존
SELECT * FROM EMPLOYEES
WHERE gender||' '|| last_name = 'M Radwan';

-- 개선
SELECT * FROM EMPLOYEES
WHERE gender='M'
    AND last_name = 'Radwan';

SELECT *
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN TO_DATE('') AND TO_DATE('')
;

SELECT FIRST_NAME, LAST_NAME, EMP_NO
FROM EMPLOYEES
WHERE EMP_NO BETWEEN 10300 AND 10309;

SELECT E.EMP_NO, E.FIRST_NAME, E.LAST_NAME, D.DEPT_NO
FROM EMPLOYEES E, DEPT_MANAGER D
WHERE E.EMP_NO = D.EMP_NO
;

SELECT COUNT(DISTINCT E.EMP_NO) AS CNT
FROM EMPLOYEES E,
    (SELECT EMP_NO
    FROM SALARIES
    WHERE SALARY > 5e4) S
WHERE E.EMP_NO = S.EMP_NO
;

SELECT COUNT(EMP_NO) AS CNT
FROM EMPLOYEES E
WHERE EXISTS (SELECT 1
              FROM SALARIES S
              WHERE S.EMP_NO = E.EMP_NO
              AND S.SALARY>5e4);
;




SELECT * FROM table(DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'ALLSTATS LAST'));

SELECT index_name, table_name, uniqueness
FROM user_indexes
WHERE table_name = 'EMPLOYEES';

SELECT * FROM EMPLOYEES;