-- 예제
WITH DepartmentSalary AS (
	SELECT DEPARTMENT_ID, ROUND(AVG(SALARY),2) AS AVG_SALARY
	FROM EMPLOYEES
	GROUP BY DEPARTMENT_ID
	ORDER BY DEPARTMENT_ID NULLS LAST)
SELECT *
FROM DepartmentSalary
WHERE AVG_SALARY > 5e3;

-- 재귀 CTE
WITH NUMBERS (NUM) AS (
	SELECT 1 AS NUM
	FROM DUAL
	UNION ALL
	SELECT NUM +1 AS NUM
	FROM NUMBERS
	WHERE NUM < 10
)
SELECT B.NUM
FROM NUMBERS B;


EXPLAIN PLAN FOR
SELECT * FROM EMPLOYEES;

EXPLAIN PLAN FOR
WITH DepartmentSalary AS (
	SELECT DEPARTMENT_ID, ROUND(AVG(SALARY),2) AS AVG_SALARY
	FROM EMPLOYEES
	GROUP BY DEPARTMENT_ID
	ORDER BY DEPARTMENT_ID NULLS LAST)
SELECT *
FROM DepartmentSalary
WHERE AVG_SALARY > 5e3;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
ALTER SESSION SET STATISTICS_LEVEL=ALL;
SELECT * FROM EMPLOYEES_VIEW;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'ALLSTATS LAST'));

SELECT sql_id, child_number, plan_hash_value, last_active_time
FROM   v$sql
WHERE  sql_id = '34yp8vd85uzyg';

SELECT DISTINCT child_number
FROM   v$sql
WHERE  sql_id = '34yp8vd85uzyg';