SELECT E.NAME AS EMPLOYEE_NAME,
       NVL(JH.JOB_ID, 'No Change') AS JOB_HISTORY
FROM EMPLOYEES E
LEFT OUTER JOIN JOB_HISTORY JH
ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
;

SELECT E.NAME AS EMPLOYEE_NAME,
       NVL(E.SALARY, 0) AS SALARY,
       D.DEPARTMENT_NAME
FROM EMPLOYEES E
LEFT OUTER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.NAME LIKE '%Employee 1%'
ORDER BY D.DEPARTMENT_NAME
;

--최근 6개월 거래 내역 조회
SELECT T.ACCOUNT_ID, 
       T.AMOUNT, 
       TO_CHAR(T.TRANSACTION_DATE, 'YYYY-MM-DD HH24:MI:SS') AS TRAN_DATE,
       C.CUSTOMER_ID,
       C.NAME
FROM TRANSACTIONS T, ACCOUNTS A, CUSTOMERS C
WHERE T.ACCOUNT_ID = A.ACCOUNT_ID
AND A.CUSTOMER_ID = C.CUSTOMER_ID
AND MONTHS_BETWEEN(SYSDATE, T.TRANSACTION_DATE)<= 6
;

SELECT COUNT(*) C
FROM EMPLOYEES E
WHERE E.SALARY BETWEEN 7e3 AND 1.5e4
GROUP BY department_id
HAVING COUNT(*) >= 5
ORDER BY C DESC
;