CREATE TABLE "ACCOUNTS" (
	"ACCOUNT_ID"	NUMBER(20)		NOT NULL,
	"USER_ID"	VARCHAR(64)		NOT NULL,
	"STATUS"	VARCHAR(5)		NULL,
	"TYPE"	VARCHAR(5)		NULL,
	"PASSWORD"	VARCHAR(20)		NULL,
	"OPEN_DATE"	DATE		NULL,
	"CLOSE_DATE"	DATE		NULL,
	"WITHHOLDING"	NUMBER(20,2)		NULL,
	"DEPOSIT"	NUMBER(20,2)		NULL,
	"CREATE_TIME"	DATE		NULL,
	"UPDATE_TIME"	DATE		NULL
);

CREATE TABLE "FUNDS" (
	"SEQUENCE"	NUMBER(2)		NOT NULL,
	"PRODUCT_ID"	NUMBER(10)		NOT NULL,
	"STOCK_TICKER"	VARCHAR(8)		NOT NULL,
	"PORTION"	NUMBER(4,2)		NULL,
	"PROFIT"	NUMBER(16,2)		NULL,
	"AMOUNT"	NUMBER(16,2)		NULL,
	"CREATE_TIME"	DATE		NULL,
	"UPDATE_TIME"	DATE		NULL
);

CREATE TABLE "HOLDINGS" (
	"SEQUENCE"	NUMBER(4)		NOT NULL,
	"ACCOUNT_ID"	NUMBER(20)		NOT NULL,
	"STOCK_TICKER"	VARCHAR(8)		NOT NULL,
	"PRODUCT_ID"	NUMBER(10)		NOT NULL,
	"QUANTITY"	NUMBER(20, 6)		NULL,
	"CREAETE_TIME"	DATE		NULL,
	"UPDATE_TIME"	DATE		NULL
);

CREATE TABLE "PRICES" (
	"BASE_DATE"	DATE		NOT NULL,
	"STOCK_TICKER"	VARCHAR(8)		NOT NULL,
	"OPEN"	NUMBER(10,2)		NULL,
	"HIGH"	NUMBER(10,2)		NULL,
	"LOW"	NUMBER(10,2)		NULL,
	"CLOSE"	NUMBER(10,2)		NULL,
	"VOLUME"	NUMBER(17)		NULL,
	"CREATE_TIME"	DATE		NULL,
	"UPDATE_TIME"	DATE		NULL
);

CREATE TABLE "USERS" (
	"USER_ID"	VARCHAR(64)		NOT NULL,
	"PASSWORD"	VARCHAR(20)		NULL,
	"NAME"	VARCHAR(20)		NULL,
	"STATUS"	VARCHAR(4)		NULL,
	"TYPE"	VARCHAR(4)		NULL,
	"EMAIL"	VARCHAR(40)		NULL,
	"PHONE_NUMBER"	VARCHAR(20)		NULL,
	"AGE"	NUMBER(3)		NULL,
	"BIRTH_DATE"	DATE		NULL,
	"GENDER"	VARCHAR(4)		NULL,
	"INCOME"	NUMBER(20,2)		NULL,
	"TENDENCY_SELF"	NUMBER(1)		NULL,
	"TENDENCY_AI"	NUMBER(1)		NULL,
	"CREATE_TIME"	DATE		NULL,
	"UPDATE_TIME"	DATE		NULL
);

CREATE TABLE "PRODUCTS" (
	"PRODUCT_ID"	NUMBER(10)		NOT NULL,
	"CLASS_CODE"	NUMBER(2)		NULL,
	"NAME"	VARCHAR(20)		NULL,
	"OPERATOR"	VARCHAR(10)		NULL,
	"CHARGE"	NUMBER(4,2)		NULL,
	"TENDENCY"	NUMBER(1)		NULL,
	"CREATE_TIME"	DATE		NULL,
	"UPDATE_TIME"	DATE		NULL
);

CREATE TABLE "BONDS" (
	"PRODUCT_ID"	NUMBER(10)		NOT NULL,
	"OPTION_CLASS"	NUMBER(2)		NULL,
	"INTEREST_CLASS"	NUMBER(2)		NULL,
	"YIELD"	NUMBER(4,2)		NULL,
	"DURATION"	NUMBER(3)		NULL,
	"BOND_PRICE"	NUMBER(12,2)		NULL,
	"FACE_VALUE"	NUMBER(12,2)		NULL,
	"COMPANY"	VARCHAR(20)		NULL
);

CREATE TABLE "TRANSACTIONS" (
	"TRANSACTION_ID"	NUMBER(20)		NOT NULL,
	"ACCOUNT_ID"	NUMBER(20)		NOT NULL,
	"PRODUCT_ID"	NUMBER(10)		NOT NULL,
	"STOCK_TICKER"	VARCHAR(8)		NOT NULL,
	"STATUS"	VARCHAR(5)		NULL,
	"TYPE"	VARCHAR(5)		NULL,
	"QUANTITY"	NUMBER(20,6)		NULL,
	"PRICE"	NUMBER(20,2)		NULL,
	"TRADED"	NUMBER(20,6)		NULL,
	"CREATE_TIME"	DATE		NULL,
	"UPDATE_TIME"	DATE		NULL,
	"CHARGE_RATE"	NUMBER(4,2)		NULL
);

CREATE TABLE "TRADES" (
	"TRADE_NUMBER"	NUMBER(20)		NOT NULL,
	"TRANSACTION_ID"	NUMBER(20)		NOT NULL,
	"BUYER_ACCOUNT_NUMBER"	NUMBER(20)		NULL,
	"SELLER_ACCOUNT_NUMBER"	NUMBER(20)		NULL,
	"QUANTITY"	NUMBER(20,6)		NULL,
	"PRICE"	NUMBER(20,2)		NULL,
	"CHARGE"	NUMBER(20,2)		NULL,
	"CREATE_TIME"	DATE		NULL,
	"UPDATE_TIME"	DATE		NULL
);

CREATE TABLE "COMPANIES" (
	"BASE_DATE"	DATE		NOT NULL,
	"STOCK_TICKER"	VARCHAR(8)		NOT NULL,
	"QUARTER"	NUMBER(1)		NULL,
	"EARNINGS"	NUMBER(16,2)		NULL,
	"OPERATING_EXPENSE"	NUMBER(16,2)		NULL,
	"NET_PROFIT"	NUMBER(16,2)		NULL,
	"ASSET"	NUMBER(16,2)		NULL,
	"AMOUNT"	NUMBER(5)		NULL,
	"CREATE_TIME"	DATE		NULL,
	"UPDATE_TIME"	DATE		NULL
);

CREATE TABLE "TICKERS" (
	"STOCK_TICKER"	VARCHAR(8)		NOT NULL,
	"STATUS"	NUMBER(2)		NULL,
	"NAME"	VARCHAR(20)		NULL,
	"SECTOR"	NUMBER(3)		NULL,
	"LISTING_DATE"	DATE		NULL,
	"DELISTING_DATE"	DATE		NULL,
	"EXCHANGE_CODE"	VARCHAR(5)		NOT NULL,
	"TENDENCY"	NUMBER(1)		NULL,
	"CREATE_TIME"	DATE		NULL,
	"UPDATE_TIME"	DATE		NULL
);

ALTER TABLE "ACCOUNTS" ADD CONSTRAINT "PK_ACCOUNTS" PRIMARY KEY (
	"ACCOUNT_ID"
);

ALTER TABLE "FUNDS" ADD CONSTRAINT "PK_FUNDS" PRIMARY KEY (
	"SEQUENCE",
	"PRODUCT_ID"
);

ALTER TABLE "HOLDINGS" ADD CONSTRAINT "PK_HOLDINGS" PRIMARY KEY (
	"SEQUENCE",
	"ACCOUNT_ID"
);

ALTER TABLE "PRICES" ADD CONSTRAINT "PK_PRICES" PRIMARY KEY (
	"BASE_DATE",
	"STOCK_TICKER"
);

ALTER TABLE "USERS" ADD CONSTRAINT "PK_USERS" PRIMARY KEY (
	"USER_ID"
);

ALTER TABLE "PRODUCTS" ADD CONSTRAINT "PK_PRODUCTS" PRIMARY KEY (
	"PRODUCT_ID"
);

ALTER TABLE "BONDS" ADD CONSTRAINT "PK_BONDS" PRIMARY KEY (
	"PRODUCT_ID"
);

ALTER TABLE "TRANSACTIONS" ADD CONSTRAINT "PK_TRANSACTIONS" PRIMARY KEY (
	"TRANSACTION_ID"
);

ALTER TABLE "TRADES" ADD CONSTRAINT "PK_TRADES" PRIMARY KEY (
	"TRADE_NUMBER"
);

ALTER TABLE "COMPANIES" ADD CONSTRAINT "PK_COMPANIES" PRIMARY KEY (
	"BASE_DATE",
	"STOCK_TICKER"
);

ALTER TABLE "TICKERS" ADD CONSTRAINT "PK_TICKERS" PRIMARY KEY (
	"STOCK_TICKER"
);

ALTER TABLE "FUNDS" ADD CONSTRAINT "FK_PRODUCTS_TO_FUNDS_1" FOREIGN KEY (
	"PRODUCT_ID"
)
REFERENCES "PRODUCTS" (
	"PRODUCT_ID"
);

ALTER TABLE "HOLDINGS" ADD CONSTRAINT "FK_ACCOUNTS_TO_HOLDINGS_1" FOREIGN KEY (
	"ACCOUNT_ID"
)
REFERENCES "ACCOUNTS" (
	"ACCOUNT_ID"
);

ALTER TABLE "PRICES" ADD CONSTRAINT "FK_TICKERS_TO_PRICES_1" FOREIGN KEY (
	"STOCK_TICKER"
)
REFERENCES "TICKERS" (
	"STOCK_TICKER"
);

ALTER TABLE "BONDS" ADD CONSTRAINT "FK_PRODUCTS_TO_BONDS_1" FOREIGN KEY (
	"PRODUCT_ID"
)
REFERENCES "PRODUCTS" (
	"PRODUCT_ID"
);

ALTER TABLE "COMPANIES" ADD CONSTRAINT "FK_TICKERS_TO_COMPANIES_1" FOREIGN KEY (
	"STOCK_TICKER"
)
REFERENCES "TICKERS" (
	"STOCK_TICKER"
);

