CREATE VIEW LOANS_VIEW AS
    SELECT
        LOAN_ID, CUSTOMER_ID,
        (SELECT NAME FROM CUSTOMERS WHERE CUSTOMER_ID = L.CUSTOMER_ID) AS CUSTOMER_NAME,
        BRANCH_ID,
        (SELECT NAME FROM BRANCHES WHERE BRANCH_ID = L.BRANCH_ID) AS BRANCH_NAME,
        AMOUNT, LOAN_DATE, STATUS
    FROM LOANS L
;


CREATE VIEW EMPLOYEES_VIEW AS
    SELECT
        EMPLOYEE_ID, NAME, MANAGER_ID,
        (SELECT NAME FROM EMPLOYEES WHERE E.MANAGER_ID = EMPLOYEE_ID) AS MANAGER_NAME,
        SALARY, JOB_ID, DEPARTMENT_ID,
        (SELECT DEPARTMENT_NAME FROM DEPARTMENTS WHERE DEPARTMENT_ID = E.DEPARTMENT_ID) AS DEPARTMENT_NAME,
        HIRE_DATE
    FROM EMPLOYEES E;

CREATE VIEW HIERARCHICAL_EMPLOYEES_VIEW AS
    SELECT
        LEVEL LV, EMPLOYEE_ID, NAME, MANAGER_ID, MANAGER_NAME,
        SALARY, JOB_ID, DEPARTMENT_NAME, HIRE_DATE,
        SYS_CONNECT_BY_PATH(NAME, '->') AS NAME_PATH,
        SYS_CONNECT_BY_PATH(DEPARTMENT_NAME, '->') AS DEPARTMENT_PATH
    FROM EMPLOYEES_VIEW
    START WITH MANAGER_ID IS NULL
    CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
;


CREATE VIEW HIERARCHICAL_SHOPPING_CATEGORIES_VIEW AS
    SELECT LEVEL AS LEVEL, CATEGORY_ID, PARENT_CATEGORY_ID, CATEGORY_NAME
    FROM SHOPPING_CATEGORIES
    START WITH PARENT_CATEGORY_ID IS NULL
    CONNECT BY PRIOR CATEGORY_ID = PARENT_CATEGORY_ID
;


CREATE VIEW TRANSACTIONS_VIEW AS
    SELECT
        TRANSACTION_ID, T.ACCOUNT_ID,
        C.CUSTOMER_ID CUSTOMER_ID,
        C.NAME CUSTOMER_NAME, EMAIL, PHONE, ADDRESS,
        A.CREATED_AT ACCOUNT_CREATED_AT,
        C.CREATED_AT CUSTOMER_CREATED_AT,
        BALANCE, AMOUNT, TRANSACTION_TYPE, TRANSACTION_DATE
    FROM TRANSACTIONS T
    LEFT JOIN ACCOUNTS A
        ON T.ACCOUNT_ID = A.ACCOUNT_ID
    LEFT OUTER JOIN CUSTOMERS C
        ON C.CUSTOMER_ID = A.CUSTOMER_ID
;






--
SELECT
    (SELECT NAME FROM BRANCHES WHERE BRANCH_ID = T.BRANCH_ID) NAME,
    SUM_AMOUNT, AVG_AMOUNT
FROM
    (SELECT
        DISTINCT BRANCH_ID,
        SUM(AMOUNT) OVER(PARTITION BY BRANCH_ID) SUM_AMOUNT,
        ROUND(AVG(AMOUNT) OVER(),2) AVG_AMOUNT
    FROM LOANS_VIEW) T
WHERE SUM_AMOUNT < AVG_AMOUNT
;

SELECT
    EMPLOYEE_ID, NAME,
    NVL(MANAGER_NAME,'No Manager') AS MANAGER_NAME,
    NVL((SELECT DEPARTMENT_NAME FROM EMPLOYEES_VIEW WHERE EMPLOYEE_ID= E.MANAGER_ID),'No Manager') AS MANAGER_DEPARTMENT
FROM EMPLOYEES_VIEW E
;

SELECT
    E1.EMPLOYEE_ID, E1.NAME,
    NVL(E2.NAME,'No Manager') AS MANAGER_NAME,
    NVL((SELECT DEPARTMENT_NAME FROM DEPARTMENTS WHERE E2.DEPARTMENT_ID=DEPARTMENT_ID),'NO DEPARTMENT') MAN_DEP_NAME
FROM EMPLOYEES E1
LEFT OUTER JOIN EMPLOYEES E2
    ON E1.MANAGER_ID = E2.EMPLOYEE_ID
;

SELECT
    EMPLOYEE_ID, NAME,
    SALARY, ROUND(100*SALARY/TSAL,2)
FROM
    (SELECT
        EMPLOYEE_ID, NAME, SALARY,
        SUM(SALARY) OVER() TSAL
    FROM EMPLOYEES
    WHERE SALARY IS NOT NULL)
ORDER BY SALARY DESC
;

SELECT * FROM(
SELECT
    ACCOUNT_ID,
    MAX(AMOUNT) OVER(PARTITION BY ACCOUNT_ID) AS MAX_AMOUNT,
    DENSE_RANK() OVER(ORDER BY AMOUNT DESC)AS RN
FROM TRANSACTIONS)
WHERE RN <= 5
;

SELECT 
    DEPARTMENT_ID,
    MAX(SALARY) - MIN(SALARY) SAL_DIFF
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;


SELECT
    EMPLOYEE_ID, NAME, SALARY, ROUND(AVG_SAL), ROUND(SALARY - AVG_SAL) SAL_DIF
FROM (
    SELECT
        EMPLOYEE_ID, NAME, SALARY,
        AVG(SALARY) OVER(PARTITION BY DEPARTMENT_ID) AS AVG_SAL
    FROM EMPLOYEES)
;


SELECT
    MAX(SYS_CONNECT_BY_PATH(NAME,'>')) PATH
FROM
    employees_view
START WITH NAME  = 'Employee 241'
CONNECT BY EMPLOYEE_ID = PRIOR MANAGER_ID
;

SELECT
    SALARY, NAME
FROM EMPLOYEES
ORDER BY SALARY DESC NULLS LAST, NAME
FETCH FIRST 10 ROWS ONLY
;

SELECT
    NVL(TO_CHAR(HIRE_DATE,'YYYY'), 'ALL YEARS') AS YEAR,
    SUM(SALARY)
FROM EMPLOYEES
GROUP BY ROLLUP(TO_CHAR(HIRE_DATE,'YYYY'))
;

SELECT
    DEPARTMENT_NAME, JOB_ID,
    SUM(SALARY) AS SAL
FROM EMPLOYEES_VIEW
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY GROUPING SETS(DEPARTMENT_NAME, JOB_ID, ())
ORDER BY DEPARTMENT_NAME, JOB_ID
;

SELECT
    DEPARTMENT_ID, NAME, SALARY,
    SUM(SALARY) OVER(PARTITION BY DEPARTMENT_ID
        ORDER BY SALARY RANGE BETWEEN 100 PRECEDING
        AND 100 FOLLOWING) AS TSAL
FROM EMPLOYEES;

SELECT
    EMPLOYEE_ID, SALARY,
    CASE
        WHEN AVG(SALARY) OVER(PARTITION BY JOB_ID) <= SALARY
            THEN '직무 평균 이상'
        ELSE '직무 평균 이하'
    END DSAL,
    CASE
        WHEN AVG(SALARY) OVER() <= SALARY
            THEN '전체 평균 이상'
        ELSE '전체 평균 이하'
    END TSAL
FROM EMPLOYEES
WHERE SALARY IS NOT NULL
;






