CREATE TABLE TUSER (
    IDUSER       NUMBER(10)      NOT NULL,
    NAME         VARCHAR2(50 CHAR),
    AGE          NUMBER(3),
    GENDER       NUMBER(1), --0:남자, 1:여자
    ADDRESS      VARCHAR2(100 CHAR),
    EMAIL        VARCHAR2(50 CHAR),
    PHONE        VARCHAR2(20 CHAR),
    PASSWORD     VARCHAR2(50 CHAR),
    CONSTRAINT PK_USER PRIMARY KEY (IDUSER)
);

CREATE TABLE BANK (
    IDBANK   NUMBER(10)       NOT NULL,
    NAME     VARCHAR2(10 CHAR) NOT NULL,
    CONSTRAINT PK_BANK PRIMARY KEY (IDBANK)
);
CREATE TABLE TACCOUNT (
    IDACCOUNT      NUMBER(10)       NOT NULL,
    IDBANK         NUMBER(10)       NOT NULL,
    BALANCE        NUMBER(15)       DEFAULT 0,
    ACCOUNTNUMBER  VARCHAR2(20 CHAR),
    CREATEDATE     DATE             DEFAULT SYSDATE,
    PW             NUMBER(10),
    ISDORMANT      NUMBER(1)        DEFAULT 0,  -- 0: 사용중, 1: 휴면
    USER_IDUSER    NUMBER(10)       NOT NULL,
    CONSTRAINT PK_ACCOUNT PRIMARY KEY (IDACCOUNT),
    CONSTRAINT FK_ACCOUNT_BANK FOREIGN KEY (IDBANK)
        REFERENCES BANK(IDBANK),
    CONSTRAINT FK_ACCOUNT_USER FOREIGN KEY (USER_IDUSER)
        REFERENCES TUSER(IDUSER)
);

CREATE TABLE TRANSMISSION (
    IDTRANSACTION     NUMBER(10)     NOT NULL,
    ACCOUNT_IDACCOUNT NUMBER(10)     NOT NULL,
    ACCOUNT_IDBANK    NUMBER(10),
    AMOUNT            NUMBER(15),
    "DATE"            DATE           DEFAULT SYSDATE, 
    ISUPDATE          NUMBER(1)      DEFAULT 0,  -- 0: 일반, 1: 정정 또는 업데이트
    BALANCE           NUMBER(15),
    CONSTRAINT PK_TRANSMISSION PRIMARY KEY (IDTRANSACTION),
    CONSTRAINT FK_TRANSMISSION_ACCOUNT FOREIGN KEY (ACCOUNT_IDACCOUNT)
        REFERENCES TACCOUNT(IDACCOUNT),
    CONSTRAINT FK_TRANSMISSION_BANK FOREIGN KEY (ACCOUNT_IDBANK)
        REFERENCES BANK(IDBANK)
);

CREATE TABLE CARD (
    IDCARD            NUMBER(10)       NOT NULL,
    NAMECARD          VARCHAR2(50 CHAR),
    ACCOUNT_IDACCOUNT NUMBER(10),
    ISTRANSPORTATION  NUMBER(1)        DEFAULT 0,  -- 0: 일반카드, 1: 교통기능포함
    ISCHECK           NUMBER(1)        DEFAULT 0,  -- 0: 신용카드, 1: 체크카드
    CONSTRAINT PK_CARD PRIMARY KEY (IDCARD),
    CONSTRAINT FK_CARD_ACCOUNT FOREIGN KEY (ACCOUNT_IDACCOUNT)
        REFERENCES TACCOUNT(IDACCOUNT)
);

CREATE TABLE CARD_TRANSACTION (
    IDTRANSACTION   NUMBER(10)     NOT NULL,
    CARD_IDCARD     NUMBER(10)     NOT NULL,
    "DATE"          DATE           DEFAULT SYSDATE,
    TRANSACTIONTIME DATE,
    AMOUNT          NUMBER(15),
    COMPANY_IDCOMPANY NUMBER(10),
    CONSTRAINT PK_CARD_TRANSACTION PRIMARY KEY (IDTRANSACTION),
    CONSTRAINT FK_CARD_TRANSACTION_CARD FOREIGN KEY (CARD_IDCARD)
        REFERENCES CARD(IDCARD),
    CONSTRAINT FK_CARD_TRANSACTION_COMPANY FOREIGN KEY (COMPANY_IDCOMPANY)
        REFERENCES COMPANY(IDCOMPANY)
);

CREATE TABLE COMPANY (
    IDCOMPANY     NUMBER(10)       NOT NULL,
    LOCATION      VARCHAR2(50 CHAR),
    CLASSCOMPANY  VARCHAR2(50 CHAR),
    NAMECOMPANY   VARCHAR2(50 CHAR),
    CONSTRAINT PK_COMPANY PRIMARY KEY (IDCOMPANY)
);

CREATE TABLE PRODUCT (
    IDPRODUCT       NUMBER(10)       NOT NULL,
    NAME            VARCHAR2(50 CHAR),
    FEATURE         VARCHAR2(255 CHAR),
    CATEGORY        VARCHAR2(255 CHAR),
    PRODUCTPERIOD   VARCHAR2(100 CHAR),
    PRODUCTCUSTOMER VARCHAR2(255 CHAR),
    PRODUCTINFO     VARCHAR2(255 CHAR),
    "CONDITION"     VARCHAR2(255 CHAR),
    CAUTION         VARCHAR2(255 CHAR),
    CREATEDATE      DATE   DEFAULT SYSDATE,
    UPDATEDATE      DATE,
    DELETEDATE      DATE,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (IDPRODUCT)
);

CREATE TABLE ISPRODUCT (
    IDISPRODUCT  NUMBER(10) NOT NULL,
    USER_IDUSER  NUMBER(10) NOT NULL,
    PRODUCT_IDPRODUCT NUMBER(10) NOT NULL
);

CREATE TABLE SURVEY (
    IDSURVEY          NUMBER(10)       NOT NULL,
    RESULT            VARCHAR2(255 CHAR),
    CREATEDATE        DATE  DEFAULT SYSDATE,
    UPDATEDATE        DATE,
    DELETEDATE        DATE,
    PRODUCT_IDPRODUCT NUMBER(10),
    IDUSER            NUMBER(10)
);

CREATE TABLE PRODUCTRATE (
    IDPRODUCT  NUMBER(10)       NOT NULL,
    MAXRATE    NUMBER(5,2),     -- 예: 99.99 형식
    MINRATE    NUMBER(5,2),
    TYPE       VARCHAR2(50 CHAR)
);


INSERT INTO TUSER (IDUSER, NAME, AGE, GENDER, ADDRESS, EMAIL, PHONE, PASSWORD)
VALUES (1, 'ALICE KIM', 28, 1, 'Seoul', 'alice.kim@dauo.co.kr', '010-0000-0000', 'PA$$W@RD');


INSERT INTO COMPANY
(
    IDCOMPANY,
    LOCATION,
    CLASSCOMPANY,
    NAMECOMPANY
)
VALUES
(
    1,
    'Seoul',
    'IT',
    'Daou Company'
);

INSERT INTO PRODUCT
(
    IDPRODUCT,
    NAME,
    FEATURE,
    CATEGORY,
    PRODUCTPERIOD,
    PRODUCTCUSTOMER,
    PRODUCTINFO,
    "CONDITION",
    CAUTION,
    CREATEDATE
)
VALUES
(
    1,
    'DAOU Savings',
    'High interest',
    'Deposit',
    '1 Year',
    'Adult',
    'This is a deposit product',
    'Min deposit 1 year',
    'Early termination fee',
    SYSDATE
);

INSERT INTO PRODUCTRATE
(
    IDPRODUCT,
    MAXRATE,
    MINRATE,
    TYPE
)
VALUES
(
    1,     -- PRODUCT 테이블의 IDPRODUCT=1 참조
    3.50,
    1.50,
    'Savings'
);

INSERT INTO TACCOUNT
(
    IDACCOUNT,
    IDBANK,
    BALANCE,
    ACCOUNTNUMBER,
    CREATEDATE,
    PW,
    ISDORMANT,
    USER_IDUSER
)
VALUES
(
    1,
    1,
    100000,
    '123-4567-7890',
    SYSDATE,
    1234,
    0,  -- 0: 정상, 1: 휴면
    1
);

INSERT INTO TRANSMISSION
(
    IDTRANSACTION,
    ACCOUNT_IDACCOUNT,
    ACCOUNT_IDBANK,
    AMOUNT,
    "DATE",
    ISUPDATE,
    BALANCE
)
VALUES
(
    1,
    1,
    1,
    5000,
    SYSDATE,
    0,
    95000
);

INSERT INTO CARD
(
    IDCARD,
    NAMECARD,
    ACCOUNT_IDACCOUNT,
    ISTRANSPORTATION,
    ISCHECK
)
VALUES
(
    1,
    'DAOU Platinum',
    1,
    1,  -- 교통카드 기능 포함
    0   -- 0: 신용카드, 1: 체크카드
);

INSERT INTO CARD_TRANSACTION
(
    IDTRANSACTION,
    CARD_IDCARD,
    "DATE",
    TRANSACTIONTIME,
    AMOUNT,
    COMPANY_IDCOMPANY
)
VALUES
(
    1,
    1,
    SYSDATE,
    SYSTIMESTAMP,
    20000,
    1
);

INSERT INTO ISPRODUCT
(
    IDISPRODUCT,
    USER_IDUSER,
    PRODUCT_IDPRODUCT
)
VALUES
(
    1,
    1,
    1
);

INSERT INTO SURVEY
(
    IDSURVEY,
    RESULT,
    CREATEDATE,
    PRODUCT_IDPRODUCT,
    IDUSER
)
VALUES
(
    1,
    'Very Satisfied',
    SYSDATE,
    1,
    1
);

INSERT INTO BANK
(
    IDBANK,
    NAME
)
VALUES
(
    1,
    'DAOU BANK'
);