-- 실습 7
SELECT B.NAME, L.CUSTOMER_ID, L.AMOUNT
FROM BRANCHES B
LEFT JOIN LOANS L
    ON B.BRANCH_ID = L.BRANCH_ID
;

SELECT C.NAME, C.EMAIL
FROM CUSTOMERS C
LEFT JOIN ACCOUNTS A
    ON C.CUSTOMER_ID = A.CUSTOMER_ID
WHERE A.BALANCE >= 5e4
;

SELECT C.NAME AS NAME, L.AMOUNT AS AMOUNT
FROM LOANS L
LEFT JOIN CUSTOMERS C
    ON L.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE L.STATUS = 'PENDING'
;
