-- 연습 문제
-- 1
SELECT E.NAME, D.LOCATION
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
;

-- 2
SELECT E1.NAME, E2.NAME
FROM EMPLOYEES E1
LEFT JOIN EMPLOYEES E2
    ON E1.EMPLOYEE_ID = E2.MANAGER_ID
;


-- 3번 급여가 NULL인 경우 N/A 반환
SELECT NAME, NVL(to_char(SALARY), 'N/A') AS SALARY
FROM EMPLOYEES;

-- 4
SELECT NAME, SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID
    FROM DEPARTMENTS
    WHERE LOCATION = 'Chicago'
    )
;

-- 5
SELECT E.NAME, E.SALARY, D.DEPARTMENT_NAME AS DEPARTMENT
FROM (SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 5e3 AND 1e4) E
INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
;

-- 6번 최근 3개월 내 입사한 직원
SELECT NAME, HIRE_DATE
FROM EMPLOYEES
WHERE MONTHS_BETWEEN(SYSDATE, HIRE_DATE) <= 3
;


-- 7
SELECT
    E.NAME, D.DEPARTMENT_NAME
FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E
    ON D.MANAGER_ID = E.EMPLOYEE_ID  
;

-- 8
SELECT JOB_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY JOB_ID
;
-- 9번 부서별 평균 급여
SELECT D2.DEPARTMENT_NAME, D1.AVG_SALARY
FROM (SELECT
        D.DEPARTMENT_ID,
        CEIL(AVG(E.SALARY)) AS AVG_SALARY
    FROM DEPARTMENTS D 
    JOIN EMPLOYEES E
        ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
    GROUP BY D.DEPARTMENT_ID) D1
JOIN DEPARTMENTS D2
    ON D2.DEPARTMENT_ID = D1.DEPARTMENT_ID
;


-- 10번 직원의 총 급여 합계
SELECT SUM(SALARY)
FROM EMPLOYEES
;

-- 11 대출 정보와 고객 이름 조회
SELECT L.AMOUNT, C.NAME
FROM LOANS L
JOIN CUSTOMERS C
    ON L.CUSTOMER_ID = C.CUSTOMER_ID
ORDER BY L.AMOUNT DESC
;

-- 12 대출 상태별 고객 수
SELECT STATUS, COUNT(DISTINCT(CUSTOMER_ID))
FROM LOANS
GROUP BY STATUS
;


-- 13 직원이 가장 적은 부서
SELECT *
FROM (SELECT DEPARTMENT_ID, COUNT(*) AS NUMEBR_OF_MEMBER
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID IS NOT NULL
    GROUP BY DEPARTMENT_ID
    ORDER BY COUNT(*) ) 
WHERE ROWNUM = 1
;


-- 14 월별 신규 고객 수
SELECT SUBSTR(TRUNC(CREATED_AT, 'MM'),1,5) AS CREATED_MONTH, COUNT(*)
FROM CUSTOMERS
GROUP BY TRUNC(CREATED_AT, 'MM')
ORDER BY CREATED_MONTH
;

-- 15 상품 카테고리 계층 구조 조회
SELECT
    S1.CATEGORY_NAME,
    S2.CATEGORY_NAME AS PARENT_CATEGORY 
FROM SHOPPING_CATEGORIES S1
LEFT JOIN SHOPPING_CATEGORIES S2
    ON S1.PARENT_CATEGORY_ID = S2.CATEGORY_ID
;

-- 16 특정 지점의 대출 합계
SELECT FLOOR(SUM(AMOUNT)) AS TOTAL_LOAN
FROM LOANS
WHERE BRANCH_ID = (SELECT BRANCH_ID
FROM BRANCHES B
WHERE B.NAME = 'Branch 8')
;

--17 직무별 직원 평균 급여와 급여 등급 조회
SELECT JOB_ID,
    CASE
        WHEN AVG(SALARY) >= 8e3 THEN 'HIGH'
        WHEN AVG(SALARY) >= 6e3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS SALARY_LEVEL
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING AVG(SALARY) >= 5e3
ORDER BY AVG(SALARY) DESC
;


-- 18 고객별 거래 내역
SELECT C.NAME, SUM(T.AMOUNT)
FROM ACCOUNTS A
JOIN TRANSACTIONS T
    ON A.ACCOUNT_ID = T.ACCOUNT_ID
JOIN CUSTOMERS C
    ON C.CUSTOMER_ID = A.CUSTOMER_ID
GROUP BY C.NAME
ORDER BY TO_NUMBER(SUBSTR(C.NAME,10))
--ORDER BY LENGTH(C.NAME), C.NAME
;


-- 19 부서별 직원의 평균 입사일 차이
SELECT D.DEPARTMENT_NAME, ROUND(AVG(J.END_DATE - J.START_DATE), 2) AS WORK_DAYS
FROM JOB_HISTORY J
LEFT JOIN EMPLOYEES E
    ON E.EMPLOYEE_ID = J.EMPLOYEE_ID
LEFT JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME
ORDER BY DEPARTMENT_NAME
;


-- 20 대출 금액 상위 5명 고객 조회
SELECT C.NAME, T.TOTAL_LOAN
FROM (
    SELECT C.CUSTOMER_ID, SUM(L.AMOUNT) AS TOTAL_LOAN
    FROM CUSTOMERS C
    LEFT JOIN LOANS L
        ON C.CUSTOMER_ID = L.CUSTOMER_ID
    GROUP BY C.CUSTOMER_ID
    ORDER BY SUM(L.AMOUNT) DESC NULLS LAST) T
LEFT JOIN CUSTOMERS C
    ON C.CUSTOMER_ID = T.CUSTOMER_ID
WHERE ROWNUM <=5
;

SELECT *
FROM(
    SELECT C.NAME, SUM(L.AMOUNT) AS TOTAL_LOAN
    FROM CUSTOMERS C
    LEFT JOIN LOANS L
        ON C.CUSTOMER_ID = L.CUSTOMER_ID
    GROUP BY C.CUSTOMER_ID, C.NAME
    ORDER BY SUM(L.AMOUNT) DESC NULLS LAST, C.NAME
)
WHERE ROWNUM <= 5
;