-- 실습 1
SELECT NAME,EMAIL FROM CUSTOMERS;
SELECT ACCOUNT_ID, BALANCE FROM ACCOUNTS;
SELECT AMOUNT, TRANSACTION_TYPE FROM TRANSACTIONS;

-- 실습 2
SELECT NAME, PHONE FROM CUSTOMERS WHERE ADDRESS = 'Address 100';
SELECT ACCOUNT_ID, BALANCE FROM ACCOUNTS WHERE BALANCE > 5e4;
SELECT TRANSACTION_ID, AMOUNT FROM TRANSACTIONS WHERE AMOUNT<0;
SELECT AMOUNT, CUSTOMER_ID FROM LOANS WHERE STATUS = 'APPROVED';

-- 실습 3
SELECT NAME, EMAIL FROM CUSTOMERS WHERE PHONE LIKE '555-003%';
SELECT ACCOUNT_ID, BALANCE FROM ACCOUNTS WHERE ACCOUNT_TYPE = 'SAVINGS' AND BALANCE >= 1e4;
SELECT TRANSACTION_ID, AMOUNT FROM TRANSACTIONS WHERE TRANSACTION_TYPE = 'DEPOSIT' AND AMOUNT >= 1e3;
SELECT LOAN_ID, AMOUNT FROM LOANS WHERE AMOUNT>=5e4 AND STATUS = 'PENDING';


-- 실습 4
SELECT NAME FROM CUSTOMERS ORDER BY NAME;
SELECT ACCOUNT_ID, BALANCE FROM ACCOUNTS ORDER BY BALANCE;
SELECT TRANSACTION_ID, AMOUNT FROM TRANSACTIONS ORDER BY AMOUNT DESC;
SELECT LOAN_ID, CUSTOMER_ID FROM LOANS ORDER BY AMOUNT;


-- 실습 5
SELECT * FROM CUSTOMERS ORDER BY NAME, EMAIL DESC;
SELECT * FROM ACCOUNTS ORDER BY BALANCE DESC, ACCOUNT_ID;
SELECT * FROM TRANSACTIONS ORDER BY TRANSACTION_TYPE, AMOUNT DESC;
SELECT * FROM LOANS ORDER BY STATUS, AMOUNT DESC;


-- 실습 6
SELECT SUM(AMOUNT) AS TOTAL_LOAN, COUNT(*) AS COUNT_LOAN FROM LOANS WHERE STATUS = 'APPROVED';

SELECT SUM(AMOUNT) AS TOTAL_AMOUNT, TO_CHAR(TRANSACTION_DATE, 'YYYY/MM') AS MONTH
FROM TRANSACTIONS
GROUP BY TO_CHAR(TRANSACTION_DATE, 'YYYY/MM')
HAVING SUM(AMOUNT) >= 1e4
;

SELECT AVG(AMOUNT) AS AVG_LOAN, SUM(AMOUNT) AS TOTAL_LOAN
FROM LOANS
WHERE STATUS = 'APPROVED'
GROUP BY BRANCH_ID
;

-- 실습 7
SELECT B.NAME, L.CUSTOMER_ID, L.AMOUNT
FROM BRANCHES B
LEFT JOIN LOANS L
    ON B.BRANCH_ID = L.BRANCH_ID
;

SELECT C.NAME, C.EMAIL
FROM CUSTOMERS C
LEFT JOIN ACCOUNTS A
    ON C.CUSTOMER_ID = A.CUSTOMER_ID
WHERE A.BALANCE >= 5e4
;

SELECT C.NAME AS NAME, L.AMOUNT AS AMOUNT
FROM LOANS L
LEFT JOIN CUSTOMERS C
    ON L.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE L.STATUS = 'PENDING'
;
