SELECT JOB_ID,
	COUNT(*) AS CNT
FROM EMPLOYEES
GROUP BY ROLLUP(JOB_ID)
ORDER BY JOB_ID;

SELECT JOB_ID,
	COUNT(*) AS CNT
FROM EMPLOYEES
GROUP BY GROUPING SETS(JOB_ID)
ORDER BY JOB_ID;

SELECT JOB_ID, DEPARTMENT_ID,
	COUNT(*) AS CNT
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY GROUPING SETS(JOB_ID, DEPARTMENT_ID, ())
ORDER BY JOB_ID, DEPARTMENT_ID;

SELECT JOB_ID, NULL AS DEPARTMENT_ID, COUNT(*) CNT FROM EMPLOYEES GROUP BY JOB_ID
UNION ALL
SELECT NULL, DEPARTMENT_ID, COUNT(*) CNT FROM EMPLOYEES GROUP BY DEPARTMENT_ID
ORDER BY JOB_ID, DEPARTMENT_ID
;

SELECT JOB_ID, DEPARTMENT_ID,
	COUNT(*) AS CNT
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY CUBE(JOB_ID, DEPARTMENT_ID)
ORDER BY JOB_ID, DEPARTMENT_ID;


SELECT JOB_ID, DEPARTMENT_ID, GROUPING(JOB_ID),
	COUNT(*) AS CNT
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY ROLLUP((JOB_ID, DEPARTMENT_ID))
ORDER BY JOB_ID, DEPARTMENT_ID;

SELECT JOB_ID, DEPARTMENT_ID, MANAGER_ID, GROUPING(JOB_ID),
	COUNT(*) AS CNT
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY CUBE(JOB_ID, DEPARTMENT_ID,MANAGER_ID)
ORDER BY JOB_ID, DEPARTMENT_ID, MANAGER_ID;

SELECT
	CASE
		WHEN GROUPING(JOB_ID) = 0 THEN JOB_ID
		WHEN GROUPING(JOB_ID) = 1 THEN '총합'
	END JOB_ID,
	COUNT(*) CNT
--    ,
--	GROUPING(JOB_ID)
FROM EMPLOYEES
GROUP BY ROLLUP(JOB_ID)
ORDER BY JOB_ID
;

-- 사원 테이블에서 부서별로 급여의 합계를 계산하고 전체 합계를 함께 출력하시오.(부서데이터가 NULL인 사원은 제외
SELECT
    NVL(TO_CHAR(DEPARTMENT_ID), 'TOTAL') AS DEPARTMENT_ID, SUM(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY ROLLUP(DEPARTMENT_ID)
;

-- 같은 날짜에 입사한 사원이 2명 이상인 날짜와 입사한 사원수, 마지막 행은 총 직원수를 함께 출력하시오.
SELECT
    NVL(TO_CHAR(HIRE_DATE, 'YYYY-MM-DD'), 'TOTAL') AS DATE_,
    COUNT(*) AS CNT
FROM EMPLOYEES
GROUP BY ROLLUP(TO_CHAR(HIRE_DATE, 'YYYY-MM-DD'))
HAVING COUNT(*) >= 2
;

-- 각 지점별 대출 금액 합계와 모든 지점의 총합계를 출력하시오. 출력 컬럼은 지점명, 대출 금액 합계이며
-- 지점 총 합계는 All Branch로 출력하고 지점명으로 정렬하되 총합계는 맨 아래줄에 나타내시오.
SELECT 
    NVL(B.NAME, 'All Branch') AS BRANCH_NAME_,
    SUM(L.AMOUNT) AS CNT
FROM LOANS L
--WHERE STATUS='APPROVED'
LEFT JOIN BRANCHES B
    ON L.BRANCH_ID = B.BRANCH_ID
GROUP BY ROLLUP(B.NAME)
ORDER BY LENGTH(B.NAME), B.NAME
;